### PR TITLE
Fixed a bug where the value of 0xe0 would not parse correctly.

### PR DESCRIPTION
**Pull request by andy-trimble**
According to the msgpack spec, 0xe0 is a valid negative fixint value.

### CODE REVIEW

**Comment by mcollina** [comment]
Great catch! Can you add a unit test for this?

**Comment by andy-trimble** [comment]
Sure thing. It looks like 0xe0 doesn't encode correctly either. I'll fix it and add the unit test.

**Comment by mcollina** [comment]
It's negative zero encoded correctly, then? Can I merge this one?

**Comment by andy-trimble** [comment]
Hmm. Looks like I just undid #15.

**Comment by andy-trimble** [comment]
Ok. It is fixed now. I compared it to the output of the Java msgpack parser, and it is behaving correctly, even for 0xe0.

I had to revert my changes. This polluted this pull request. If you'd rather, I can create a new one without commits 139dc84 and 10a6b69.

**Comment by mcollina** [comment]
Thanks! I think this was good!

**Pull request merged**
