### PR TITLE
Fixes #39: Adds support for encoding very small and very large integers

### LINKED ISSUE #39: Encoder fails on a large negative number
The `encode` function does not seem to be prepared for encoding large negative numbers.

```javascript
require('msgpack5')().encode(-300000000)
```

> Error: not implemented yet
    at encode (.../node_modules/msgpack5/lib/encoder.js:127:13)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)

Update: @mdouglass's fork (https://github.com/mdouglass/msgpack5/commit/01a79dc10f3db6d320f98314cd954b4b7599a8be) seems to enlarge the limit before it stops working, but it may still fail to encode larger values that should be interpreted as doubles.

### PR DESCRIPTION
**Pull request by mdouglass**

### CODE REVIEW

**Comment by mdouglass** [comment]
This builds on my previous pull request to support signed int 64s. If you'd prefer, this could be committed separately, but it would leave a gap in the signed integer encoding between the largest 32-bit integer and Number.MAX_SAFE_INTEGER which would fail.

**Comment by Enet4** [comment]
Well, I admit I hadn't noticed #38 when I posted #39. Thanks for your swift efforts, nevertheless! This fix will definitely suit people better than what we had before. Maybe in the future we could introduce some means of encoding and decoding 64-bit integers without losing precision, but this patch behaves in a much more predictable way.

**Comment by mdouglass** [comment]
No problem, I actually had the same fix to address on my radar for today. Your issue report just gave me the encouragement to open it sooner.  
It would be interesting to link in https://github.com/broofa/node-int64 and optionally use that for decoding 64-bit values.

**Comment by mcollina** [comment]
Superb!

**Pull request merged**
