### PR TITLE
Bumping tape version

### PR DESCRIPTION
**Pull request by moonglum**
* Updated the tape version
* The test command did not use the locally installed version of  tape and faucet, so it did not work when you did not install  those globally.

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks for bumping the tape version.

The test command does not need `node_modules`, as it wires things up that all modules that installs a binary can be used in the scripts. So, why do you need that change?

**Comment by moonglum** [comment]
When I run `npm test` without this change, I will get an error that the command "tape" was not found.

**Comment by mcollina** [comment]
which version of node/npm are you using?

**Comment by mcollina** [comment]
As you can see in the Travis build, there is no global installation of tape and faucet.
https://travis-ci.org/mcollina/msgpack5/jobs/61466837

**Comment by moonglum** [comment]
Ok, maybe it is because I have older versions of Node and NPM?

* Node v0.10.26
* NPM 1.4.3

But this makes it work on those old versions, too – and apart from that command everything works in 0.10 :wink:

**Comment by mcollina** [comment]
Current master `npm test` runs smoothly on node v0.10.26.

**Comment by moonglum** [comment]
Weird. Let me test it again.

**Comment by moonglum** [comment]
Weird... It works now. Sorry for the confusion, I removed everything apart from the version bump!

**Comment by mcollina** [comment]
Thanks!!

**Comment by moonglum** [comment]
You're welcome!

**Pull request merged**
