### PR TITLE
Handle an incomplete buffer

### PR DESCRIPTION
**Pull request by shinichy**
I made changes to handle an incomplete buffer better without an additional length header in Decoder class.
The main purpose of this change is to use this library for msgpack-rpc protocol (It seems working).
Thanks,

### CODE REVIEW

**Comment by mcollina** [comment]
Maybe I am missing something, but where does the already parsed data go? It seems you call `consume()` anyway. Let's consider this scenario: a BIG array comes in, and it is truncated. It parses half of it, and then it errors. Can you add a test with that use case?

I think that what can solve your problem is a different design. Instead of using a single method, you need to create a `Parser`, which includes a bl instance on which data are appended to. Now we are using recursion to store the state, and in that case you might need to code our own stack.

The current `decode()` method than can just be an alias for `return new Parser().decode(buf)`.
 
The current design is also slow :sob:, and you are adding some more duplication of the bl, which might slow things down too. The new design should be faster anyway.

Would you like to take the challenge?

Anyway, would you like helping me maintaining this module?

**Comment by shinichy** [comment]
Thanks for reviewing my code.

That test scenario is tested in 'decoding an incomplete array' in 4-bytes-length-arrays.js.
It throws IncompleteBufferError in the middle of parsing array. In this case decode(buf) doesn't consume  any byte, so decoder can decode from the beginning after the buffer becomes complete.

But you're right. Stream deserializing is better approach. I don't have enough time to tackle it right now but I will do it when I have time again.

**Comment by mcollina** [comment]
I just saw that test. Does it still work if a big array is within another object? If it does, then I misunderstood this and we can get it merged. If this is the case, can you update the README in the decode function, saying that in order to support a stream interface a user must pass in an instance of `bl`?

Anyway, would you like to help maintaining this library?

**Comment by shinichy** [comment]
I added a test to check the case and it also looks good.

I'm not sure how much I can help but sure. I can help fixing small issues.

**Comment by mcollina** [comment]
I am really tempted by this PR, as it is a feature I want in. However it is almost 50% slower than current master.

I am using this little script the benchmark:

```js
var msgpack = require('./')()
  , msg     = msgpack.encode({ hello: 'world' })
  , decode  = msgpack.decode
  , max     = 100000
  , start
  , stop
  , i

function run() {
  for (i = 0; i < max; i++) {
    decode(msg)
  }
}

//preheat
run()

start  = Date.now()
run()
stop = Date.now()
console.log('time', stop - start)
console.log('decode/s', max / (stop - start) * 1000)
```

On my macbook pro, master runs at 33000 decode/s, while this PR runs at 15000 decode/s (17k if I remove the try/catch). Both are definitely too slow, but this one is making things worse.

How about we try having a two step parse? First we calculate if we can parse, and then we parse. Or we can maintain a `pos` variable, and do not call consume altogether during each step, but only at the very last one.

I am adding you to this project, so we can collaborate to make this better. Feel free to push your branch on another branch here, and send a different PR, so I can commit there too!

**Comment by shinichy** [comment]
I sent a different PR. Could you check it?

**Pull request closed without merging**
