### PR TITLE
Improve internals and add some features

### LINKED ISSUE #52: Add an option to support predicable encoding
```js
// file: lib/encoder.js:201 function encodeObject
    for (key in obj) {
      if (obj.hasOwnProperty(key) &&
        obj[key] !== undefined &&
        typeof obj[key] !== 'function') {
        ++length
        acc.push(encode(key, true))
        acc.push(encode(obj[key], true))
      }
    }
```

this will cause the properties order is unpredicable, that will cause some digest mechanism will failed: same value in different case produce different encoded result.

### LINKED ISSUE #63: integer keys / Map encoding
In JSON and javascript , map keys have to be strings, but in MessagePack keys can be numbers.

Is there a way to force keys in a javascript object to be numbers when msgpack encoding is done?

javascript Map allows to use numbers as keys, but looks like objects encoded from a map cannot be de decoded : 

let mapExemple = new Map()
mapExemple.set(1,"map")
mapExemple.set(3,"test")

let mpackedEx = msgpack.encode(mapExemple)

console.log(msgPackDecode(mpackedEx))

> {}

### LINKED ISSUE #77: Too complicated encodeFloat function.
https://github.com/mcollina/msgpack5/blob/827ed095d6f18ed52e7f4ddafe498e1e6d0a6a77/lib/encoder.js#L314

```js
const fround = Math.fround;

function encodeFloat (obj, forceFloat64) { 
  var buf
  
  if (forceFloat64 || !fround || fround(obj) !== obj) {
    buf = Buffer.allocUnsafe(9)
    buf[0] = 0xcb
    buf.writeDoubleBE(obj, 1)
  } else {
    buf = Buffer.allocUnsafe(5)
    buf[0] = 0xca
    buf.writeFloatBE(obj, 1)
  }

  return buf
}
```

### PR DESCRIPTION
**Pull request by thephoenixofthevoid**
1. Encoder refactoring
2. Support encoding/decoding Maps instances [Fix #63 and #10 possibly]
3. Support sorting objects keys when serialization [Fix #52]
4. Fix encodeFloat implementation [Fix #77] 
5. TimestampEncoding is treated as an ext-type with type === -1 (inaccessible from user API though)

### CODE REVIEW

**Comment by thephoenixofthevoid** [comment]
I will resolve conflicts tomorrow or so --- would you please take a look at changes before that? What do you think?

**Comment by mcollina** [comment]
I’m ok with most of the changes, but it’s hard to tell right now.

You should add tests for each fixes.

**Comment by thephoenixofthevoid** [comment]
Would you please consider using cached node images in travis? I is taking almost 90% of time rebuilding it over and over.

**Comment by mcollina** [comment]
I only had issues with them.

**Comment by kevygreen** [comment]
@mcollina The #76 and #78 start to use new ECMAScript notations such as ... , => and destructuring. That won't work with the minification, and likely older browsers. Is the goal to allow those changes or should they be undone back to their simpler JS notations?

**Comment by mcollina** [comment]
Would you mind sending a followup PR?

Il giorno ven 24 mag 2019 alle 20:03 kevygreen <notifications@github.com>
ha scritto:

**Comment by kevygreen** [comment]
I'm not sure what you want to do:
Option 1: Allow new notations (somehow fix build issues) - Don't know if this is possible
Options 2: revert changes made in this PR and PR #76 that change to this style - I think this is what should be done but it is undoing some of the changes done by @thephoenixofthevoid that you accepted
This means:
 - changing => to functions
 - changing let, const to var
 - getting rid of destructuring
 - adding object property names back in
 - getting rid of ... usage

If it is Option 2, then future commits should be checked for this prior to merging too. Maybe part of the CI should test a build?

If you are good with Option 2 I can attempt to create a new PR to address the issues, then another PR for the timestamp96 stuff from #79

**Comment by mcollina** [comment]
I would prefer Option 1, fixing the build. We might have to modernize our toolkit/add babel and webpack.

**Pull request merged**
